name: Lint misc files

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck
      run: |
        shellcheck ./me
    # Doesn't work at the moment, because command does not yet know Python3.8
    # - name: Run cfn-lint
    #   run: |
    #     pip install cfn-lint
    #     cfn-lint ./cfn/*.cfn.*
