name: Lint misc files

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck
      run: |
        sudo apt install -y shellcheck
        shellcheck bin/*
    - name: Run 
      run: |
        sudo apt install -y python3-pip
        sudo pip3 install cfn-lint
        cfn-lint cfn/*.cfn.*
