name: Lint misc files

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck
      run: |
        shellcheck ./me
    - name: Run cfn-lint
      run: |
        pip install cfn-lint
        cfn-lint ./cfn/*.cfn.*
