name: Lint misc files

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck
      run: |
        apt install -y shellcheck
        shellcheck bin/*
    - name: Run 
      run: |
        apt install -y npm
        npm install cfn-lint
        cfn-lint cfn/*.cfn.*
